server.port=8081
spring.application.name=auth-service

# Disable Config Server
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/AuthenticationDB
spring.datasource.username=postgres
spring.datasource.password=lock
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka CLIENT (IMPORTANT)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=false
# Disable Config Server health check
management.health.configserver.enabled=false

# Disable Redis health check (until you actually use Redis)
management.health.redis.enabled=false


