server.port=8080
spring.application.name=api-gateway

# Disable config client (no config server yet)
spring.cloud.config.enabled=false

# Eureka registration (we want gateway to register)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway + Eureka integration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
